[2025-07-18T12:26:54.902+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T12:26:54.920+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T12:26:54.921+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T12:26:54.922+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2025-07-18T12:26:54.925+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T12:26:54.947+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T12:26:54.956+0000] {standard_task_runner.py:55} INFO - Started process 470 to run task
[2025-07-18T12:26:54.960+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmp4qzn0xvt']
[2025-07-18T12:26:54.967+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask feature_engineering
[2025-07-18T12:26:55.070+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host 0a70033a54ea
[2025-07-18T12:26:55.130+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T12:26:55.133+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T12:26:55.135+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T12:26:55.145+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T12:26:57.280+0000] {subprocess.py:93} INFO - /app/scripts/engineer.py:6: UserWarning:
[2025-07-18T12:26:57.281+0000] {subprocess.py:93} INFO - The version_base parameter is not specified.
[2025-07-18T12:26:57.282+0000] {subprocess.py:93} INFO - Please specify a compatability version level, or None.
[2025-07-18T12:26:57.282+0000] {subprocess.py:93} INFO - Will assume defaults for version 1.1
[2025-07-18T12:26:57.282+0000] {subprocess.py:93} INFO -   @hydra.main(config_path="../config", config_name="config")
[2025-07-18T12:26:57.675+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T12:26:57.692+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T12:26:57.728+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T12:26:57.731+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T12:26:57.897+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T12:26:57.906+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 9, in main
[2025-07-18T12:26:57.910+0000] {subprocess.py:93} INFO -     cfg.data.raw_path   = to_absolute_path(cfg.data.raw_path)
[2025-07-18T12:26:57.913+0000] {subprocess.py:93} INFO - omegaconf.errors.ConfigAttributeError: Key 'raw_path' is not in struct
[2025-07-18T12:26:57.917+0000] {subprocess.py:93} INFO -     full_key: data.raw_path
[2025-07-18T12:26:57.921+0000] {subprocess.py:93} INFO -     object_type=dict
[2025-07-18T12:26:57.927+0000] {subprocess.py:93} INFO - 
[2025-07-18T12:26:57.931+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T12:26:58.350+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T12:26:58.412+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T12:26:58.425+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T122654, end_date=20250718T122658
[2025-07-18T12:26:58.472+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 7 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 470)
[2025-07-18T12:26:58.538+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T12:26:58.712+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T13:38:32.209+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T13:38:32.216+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T13:38:32.217+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T13:38:32.217+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2025-07-18T13:38:32.219+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T13:38:32.227+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T13:38:32.235+0000] {standard_task_runner.py:55} INFO - Started process 302 to run task
[2025-07-18T13:38:32.239+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmp0ffwilu0']
[2025-07-18T13:38:32.244+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask feature_engineering
[2025-07-18T13:38:32.294+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host 8169abd6c4f3
[2025-07-18T13:38:32.336+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T13:38:32.338+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T13:38:32.339+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T13:38:32.346+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T13:38:33.099+0000] {subprocess.py:93} INFO - /app/scripts/engineer.py:19: UserWarning:
[2025-07-18T13:38:33.099+0000] {subprocess.py:93} INFO - The version_base parameter is not specified.
[2025-07-18T13:38:33.100+0000] {subprocess.py:93} INFO - Please specify a compatability version level, or None.
[2025-07-18T13:38:33.100+0000] {subprocess.py:93} INFO - Will assume defaults for version 1.1
[2025-07-18T13:38:33.100+0000] {subprocess.py:93} INFO -   @hydra.main(config_path="../config", config_name="config")
[2025-07-18T13:38:33.195+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T13:38:33.195+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T13:38:33.195+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T13:38:33.202+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpp0ew62kq/data/raw/adult.csv â€¦
[2025-07-18T13:38:33.203+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T13:38:33.241+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T13:38:33.241+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 25, in main
[2025-07-18T13:38:33.241+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T13:38:33.241+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T13:38:33.241+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T13:38:33.242+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T13:38:33.242+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T13:38:33.242+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T13:38:33.242+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T13:38:33.242+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T13:38:33.242+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T13:38:33.242+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T13:38:33.242+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T13:38:33.243+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T13:38:33.243+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T13:38:33.243+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T13:38:33.243+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T13:38:33.243+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpp0ew62kq/data/raw/adult.csv'
[2025-07-18T13:38:33.243+0000] {subprocess.py:93} INFO - 
[2025-07-18T13:38:33.243+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T13:38:33.353+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T13:38:33.360+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T13:38:33.363+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T133832, end_date=20250718T133833
[2025-07-18T13:38:33.372+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 6 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 302)
[2025-07-18T13:38:33.384+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T13:38:33.413+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T14:12:48.150+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T14:12:48.155+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T14:12:48.156+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T14:12:48.156+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2025-07-18T14:12:48.156+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T14:12:48.162+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T14:12:48.169+0000] {standard_task_runner.py:55} INFO - Started process 332 to run task
[2025-07-18T14:12:48.171+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpb7wg1kos']
[2025-07-18T14:12:48.177+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask feature_engineering
[2025-07-18T14:12:48.217+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host f6bb4ae5b7b3
[2025-07-18T14:12:48.250+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T14:12:48.251+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T14:12:48.252+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T14:12:48.258+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T14:12:48.933+0000] {subprocess.py:93} INFO - /app/scripts/engineer.py:19: UserWarning:
[2025-07-18T14:12:48.933+0000] {subprocess.py:93} INFO - The version_base parameter is not specified.
[2025-07-18T14:12:48.933+0000] {subprocess.py:93} INFO - Please specify a compatability version level, or None.
[2025-07-18T14:12:48.933+0000] {subprocess.py:93} INFO - Will assume defaults for version 1.1
[2025-07-18T14:12:48.934+0000] {subprocess.py:93} INFO -   @hydra.main(config_path="../config", config_name="config")
[2025-07-18T14:12:49.037+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T14:12:49.037+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T14:12:49.038+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T14:12:49.044+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmp7_opznbq/data/raw/adult.csv â€¦
[2025-07-18T14:12:49.044+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T14:12:49.081+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T14:12:49.081+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 25, in main
[2025-07-18T14:12:49.081+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T14:12:49.081+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T14:12:49.082+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T14:12:49.082+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T14:12:49.082+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T14:12:49.082+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T14:12:49.082+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T14:12:49.082+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T14:12:49.083+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T14:12:49.083+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T14:12:49.083+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T14:12:49.083+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T14:12:49.083+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T14:12:49.083+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T14:12:49.083+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T14:12:49.083+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmp7_opznbq/data/raw/adult.csv'
[2025-07-18T14:12:49.084+0000] {subprocess.py:93} INFO - 
[2025-07-18T14:12:49.084+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T14:12:49.185+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T14:12:49.194+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T14:12:49.196+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T141248, end_date=20250718T141249
[2025-07-18T14:12:49.203+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 6 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 332)
[2025-07-18T14:12:49.230+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T14:12:49.246+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T15:37:23.607+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:37:23.612+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:37:23.612+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:37:23.612+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2025-07-18T15:37:23.612+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:37:23.619+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T15:37:23.623+0000] {standard_task_runner.py:55} INFO - Started process 342 to run task
[2025-07-18T15:37:23.626+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpj60xgxe5']
[2025-07-18T15:37:23.628+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask feature_engineering
[2025-07-18T15:37:23.669+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host 95d08d32c22b
[2025-07-18T15:37:23.702+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T15:37:23.703+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T15:37:23.704+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T15:37:23.710+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T15:37:24.752+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T15:37:24.756+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T15:37:24.757+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T15:37:24.759+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpufi28mgl/data/raw/adult.csv â€¦
[2025-07-18T15:37:24.759+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T15:37:24.793+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T15:37:24.793+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T15:37:24.794+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T15:37:24.795+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T15:37:24.795+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T15:37:24.795+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T15:37:24.795+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpufi28mgl/data/raw/adult.csv'
[2025-07-18T15:37:24.795+0000] {subprocess.py:93} INFO - 
[2025-07-18T15:37:24.795+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T15:37:24.894+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T15:37:24.902+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T15:37:24.907+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T153723, end_date=20250718T153724
[2025-07-18T15:37:24.915+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 6 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 342)
[2025-07-18T15:37:24.945+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T15:37:24.960+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T16:00:00.199+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T16:00:00.206+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T16:00:00.207+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T16:00:00.208+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2025-07-18T16:00:00.209+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T16:00:00.222+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T16:00:00.225+0000] {standard_task_runner.py:55} INFO - Started process 336 to run task
[2025-07-18T16:00:00.231+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpkrorjxi3']
[2025-07-18T16:00:00.236+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask feature_engineering
[2025-07-18T16:00:00.285+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host e1a2c151e318
[2025-07-18T16:00:00.319+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T16:00:00.319+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T16:00:00.320+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T16:00:00.326+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T16:00:01.371+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T16:00:01.372+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T16:00:01.372+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T16:00:01.381+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmptwuwuoe3/data/raw/adult.csv â€¦
[2025-07-18T16:00:01.383+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T16:00:01.417+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T16:00:01.417+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-18T16:00:01.417+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T16:00:01.418+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T16:00:01.418+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T16:00:01.418+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T16:00:01.418+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T16:00:01.418+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T16:00:01.418+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T16:00:01.418+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T16:00:01.419+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T16:00:01.419+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T16:00:01.419+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T16:00:01.419+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T16:00:01.419+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T16:00:01.419+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T16:00:01.419+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T16:00:01.419+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmptwuwuoe3/data/raw/adult.csv'
[2025-07-18T16:00:01.420+0000] {subprocess.py:93} INFO - 
[2025-07-18T16:00:01.420+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T16:00:01.520+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T16:00:01.529+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T16:00:01.535+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T160000, end_date=20250718T160001
[2025-07-18T16:00:01.544+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 6 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 336)
[2025-07-18T16:00:01.569+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T16:00:01.589+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
