[2025-07-18T11:54:38.948+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T11:54:38.956+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T11:54:38.957+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T11:54:38.957+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T11:54:38.957+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T11:54:38.965+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T11:54:38.969+0000] {standard_task_runner.py:55} INFO - Started process 210 to run task
[2025-07-18T11:54:38.972+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmp9azkp2u2']
[2025-07-18T11:54:38.976+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T11:54:39.013+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host 71b03233e140
[2025-07-18T11:54:39.130+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T11:54:39.159+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T11:54:39.184+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T11:54:39.208+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T11:54:39.899+0000] {subprocess.py:93} INFO - /app/scripts/engineer.py:5: UserWarning:
[2025-07-18T11:54:39.900+0000] {subprocess.py:93} INFO - The version_base parameter is not specified.
[2025-07-18T11:54:39.900+0000] {subprocess.py:93} INFO - Please specify a compatability version level, or None.
[2025-07-18T11:54:39.900+0000] {subprocess.py:93} INFO - Will assume defaults for version 1.1
[2025-07-18T11:54:39.900+0000] {subprocess.py:93} INFO -   @hydra.main(config_path="../config", config_name="config")
[2025-07-18T11:54:40.040+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T11:54:40.041+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T11:54:40.041+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T11:54:40.047+0000] {subprocess.py:93} INFO - Loading raw data from data/raw/adult.csv â€¦
[2025-07-18T11:54:40.047+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T11:54:40.083+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T11:54:40.083+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 7, in main
[2025-07-18T11:54:40.083+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T11:54:40.083+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T11:54:40.083+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T11:54:40.083+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T11:54:40.084+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T11:54:40.084+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T11:54:40.084+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T11:54:40.084+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T11:54:40.084+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T11:54:40.084+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T11:54:40.084+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T11:54:40.084+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T11:54:40.085+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T11:54:40.085+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T11:54:40.085+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T11:54:40.085+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/adult.csv'
[2025-07-18T11:54:40.085+0000] {subprocess.py:93} INFO - 
[2025-07-18T11:54:40.085+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T11:54:40.185+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T11:54:40.193+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T11:54:40.195+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T115438, end_date=20250718T115440
[2025-07-18T11:54:40.204+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 210)
[2025-07-18T11:54:40.241+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T11:54:40.261+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T12:19:27.127+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T12:19:27.132+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T12:19:27.132+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T12:19:27.132+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T12:19:27.132+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T12:19:27.137+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T12:19:27.139+0000] {standard_task_runner.py:55} INFO - Started process 401 to run task
[2025-07-18T12:19:27.141+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpk_z84rr0']
[2025-07-18T12:19:27.143+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T12:19:27.177+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host 0a70033a54ea
[2025-07-18T12:19:27.206+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T12:19:27.207+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T12:19:27.208+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T12:19:27.213+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T12:19:27.712+0000] {subprocess.py:93} INFO - /app/scripts/engineer.py:6: UserWarning:
[2025-07-18T12:19:27.712+0000] {subprocess.py:93} INFO - The version_base parameter is not specified.
[2025-07-18T12:19:27.712+0000] {subprocess.py:93} INFO - Please specify a compatability version level, or None.
[2025-07-18T12:19:27.712+0000] {subprocess.py:93} INFO - Will assume defaults for version 1.1
[2025-07-18T12:19:27.713+0000] {subprocess.py:93} INFO -   @hydra.main(config_path="../config", config_name="config")
[2025-07-18T12:19:27.804+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T12:19:27.804+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T12:19:27.804+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T12:19:27.810+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T12:19:27.844+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T12:19:27.844+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 9, in main
[2025-07-18T12:19:27.845+0000] {subprocess.py:93} INFO -     cfg.data.raw_path   = to_absolute_path(cfg.data.raw_path)
[2025-07-18T12:19:27.845+0000] {subprocess.py:93} INFO - omegaconf.errors.ConfigAttributeError: Key 'raw_path' is not in struct
[2025-07-18T12:19:27.845+0000] {subprocess.py:93} INFO -     full_key: data.raw_path
[2025-07-18T12:19:27.845+0000] {subprocess.py:93} INFO -     object_type=dict
[2025-07-18T12:19:27.845+0000] {subprocess.py:93} INFO - 
[2025-07-18T12:19:27.845+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T12:19:27.976+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T12:19:27.988+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T12:19:27.994+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T121927, end_date=20250718T121927
[2025-07-18T12:19:28.003+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 401)
[2025-07-18T12:19:28.031+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T12:19:28.048+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T13:33:30.780+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T13:33:30.786+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T13:33:30.787+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T13:33:30.787+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T13:33:30.787+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T13:33:30.795+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T13:33:30.797+0000] {standard_task_runner.py:55} INFO - Started process 216 to run task
[2025-07-18T13:33:30.799+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmp48ai904u']
[2025-07-18T13:33:30.800+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T13:33:30.844+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host 8169abd6c4f3
[2025-07-18T13:33:30.873+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T13:33:30.873+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T13:33:30.874+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T13:33:30.878+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T13:33:31.375+0000] {subprocess.py:93} INFO - /app/scripts/engineer.py:19: UserWarning:
[2025-07-18T13:33:31.376+0000] {subprocess.py:93} INFO - The version_base parameter is not specified.
[2025-07-18T13:33:31.376+0000] {subprocess.py:93} INFO - Please specify a compatability version level, or None.
[2025-07-18T13:33:31.377+0000] {subprocess.py:93} INFO - Will assume defaults for version 1.1
[2025-07-18T13:33:31.377+0000] {subprocess.py:93} INFO -   @hydra.main(config_path="../config", config_name="config")
[2025-07-18T13:33:31.493+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T13:33:31.494+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T13:33:31.495+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T13:33:31.500+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpr6qw6_bq/data/raw/adult.csv â€¦
[2025-07-18T13:33:31.502+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T13:33:31.539+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T13:33:31.542+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 25, in main
[2025-07-18T13:33:31.544+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T13:33:31.544+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T13:33:31.544+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T13:33:31.544+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T13:33:31.544+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T13:33:31.545+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T13:33:31.545+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T13:33:31.545+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T13:33:31.545+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T13:33:31.545+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T13:33:31.545+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T13:33:31.545+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T13:33:31.545+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T13:33:31.545+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T13:33:31.545+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T13:33:31.545+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpr6qw6_bq/data/raw/adult.csv'
[2025-07-18T13:33:31.546+0000] {subprocess.py:93} INFO - 
[2025-07-18T13:33:31.546+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T13:33:31.641+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T13:33:31.649+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T13:33:31.651+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T133330, end_date=20250718T133331
[2025-07-18T13:33:31.658+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 216)
[2025-07-18T13:33:31.663+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T13:33:31.678+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T14:07:46.177+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T14:07:46.182+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T14:07:46.183+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T14:07:46.183+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T14:07:46.185+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T14:07:46.190+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T14:07:46.194+0000] {standard_task_runner.py:55} INFO - Started process 247 to run task
[2025-07-18T14:07:46.196+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmp5pfrs29y']
[2025-07-18T14:07:46.197+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T14:07:46.229+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host f6bb4ae5b7b3
[2025-07-18T14:07:46.259+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T14:07:46.260+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T14:07:46.260+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T14:07:46.264+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T14:07:46.941+0000] {subprocess.py:93} INFO - /app/scripts/engineer.py:19: UserWarning:
[2025-07-18T14:07:46.946+0000] {subprocess.py:93} INFO - The version_base parameter is not specified.
[2025-07-18T14:07:46.948+0000] {subprocess.py:93} INFO - Please specify a compatability version level, or None.
[2025-07-18T14:07:46.950+0000] {subprocess.py:93} INFO - Will assume defaults for version 1.1
[2025-07-18T14:07:46.951+0000] {subprocess.py:93} INFO -   @hydra.main(config_path="../config", config_name="config")
[2025-07-18T14:07:47.283+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T14:07:47.288+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T14:07:47.291+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T14:07:47.297+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpbz34xxdg/data/raw/adult.csv â€¦
[2025-07-18T14:07:47.298+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T14:07:47.374+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T14:07:47.377+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 25, in main
[2025-07-18T14:07:47.377+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T14:07:47.378+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T14:07:47.379+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T14:07:47.379+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T14:07:47.380+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T14:07:47.380+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T14:07:47.382+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T14:07:47.383+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T14:07:47.383+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T14:07:47.383+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T14:07:47.383+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T14:07:47.384+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T14:07:47.384+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T14:07:47.384+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T14:07:47.384+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T14:07:47.384+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpbz34xxdg/data/raw/adult.csv'
[2025-07-18T14:07:47.384+0000] {subprocess.py:93} INFO - 
[2025-07-18T14:07:47.385+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T14:07:47.586+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T14:07:47.615+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T14:07:47.618+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T140746, end_date=20250718T140747
[2025-07-18T14:07:47.634+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 247)
[2025-07-18T14:07:47.646+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T14:07:47.676+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T14:25:43.259+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T14:25:43.266+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T14:25:43.266+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T14:25:43.266+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T14:25:43.266+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T14:25:43.272+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T14:25:43.276+0000] {standard_task_runner.py:55} INFO - Started process 221 to run task
[2025-07-18T14:25:43.278+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpnw5avzwi']
[2025-07-18T14:25:43.280+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T14:25:43.331+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host 462761df47da
[2025-07-18T14:25:43.372+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T14:25:43.372+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T14:25:43.373+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T14:25:43.379+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T14:25:44.131+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T14:25:44.135+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T14:25:44.137+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T14:25:44.139+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpe1t1szpd/data/raw/adult.csv â€¦
[2025-07-18T14:25:44.139+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T14:25:44.177+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T14:25:44.177+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 30, in main
[2025-07-18T14:25:44.177+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T14:25:44.177+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T14:25:44.177+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T14:25:44.177+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T14:25:44.177+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T14:25:44.177+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T14:25:44.178+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T14:25:44.178+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T14:25:44.178+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T14:25:44.178+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T14:25:44.178+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T14:25:44.178+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T14:25:44.178+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T14:25:44.178+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T14:25:44.178+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T14:25:44.178+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpe1t1szpd/data/raw/adult.csv'
[2025-07-18T14:25:44.178+0000] {subprocess.py:93} INFO - 
[2025-07-18T14:25:44.179+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T14:25:44.293+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T14:25:44.305+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T14:25:44.308+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T142543, end_date=20250718T142544
[2025-07-18T14:25:44.317+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 221)
[2025-07-18T14:25:44.326+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T14:25:44.344+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T14:31:28.103+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T14:31:28.108+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T14:31:28.109+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T14:31:28.109+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T14:31:28.109+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T14:31:28.116+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T14:31:28.118+0000] {standard_task_runner.py:55} INFO - Started process 215 to run task
[2025-07-18T14:31:28.121+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpunjpbwjz']
[2025-07-18T14:31:28.123+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T14:31:28.158+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host e601907df341
[2025-07-18T14:31:28.191+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T14:31:28.191+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T14:31:28.192+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T14:31:28.196+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T14:31:28.753+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T14:31:28.753+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T14:31:28.754+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T14:31:28.760+0000] {subprocess.py:93} INFO - Loading raw data from /app/data/raw/adult.csv â€¦
[2025-07-18T14:31:28.760+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T14:31:28.794+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T14:31:28.794+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 30, in main
[2025-07-18T14:31:28.794+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T14:31:28.794+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T14:31:28.794+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T14:31:28.795+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T14:31:28.795+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T14:31:28.795+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T14:31:28.795+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T14:31:28.795+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T14:31:28.795+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T14:31:28.795+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T14:31:28.795+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T14:31:28.795+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T14:31:28.796+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T14:31:28.796+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T14:31:28.796+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T14:31:28.796+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/app/data/raw/adult.csv'
[2025-07-18T14:31:28.796+0000] {subprocess.py:93} INFO - 
[2025-07-18T14:31:28.796+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T14:31:28.896+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T14:31:28.902+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T14:31:28.905+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T143128, end_date=20250718T143128
[2025-07-18T14:31:28.912+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 215)
[2025-07-18T14:31:28.931+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T14:31:28.945+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T15:21:41.447+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:21:41.453+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:21:41.455+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:21:41.455+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T15:21:41.455+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:21:41.465+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T15:21:41.473+0000] {standard_task_runner.py:55} INFO - Started process 252 to run task
[2025-07-18T15:21:41.475+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmprwk0ulfs']
[2025-07-18T15:21:41.477+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T15:21:41.516+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host 5bd3d7cd7066
[2025-07-18T15:21:41.547+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T15:21:41.547+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T15:21:41.547+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T15:21:41.553+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T15:21:42.708+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T15:21:42.709+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T15:21:42.709+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T15:21:42.715+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmp_ene_2sq/data/raw/adult.csv â€¦
[2025-07-18T15:21:42.715+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T15:21:42.753+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T15:21:42.753+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-18T15:21:42.753+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T15:21:42.753+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmp_ene_2sq/data/raw/adult.csv'
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO - 
[2025-07-18T15:21:42.754+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T15:21:42.883+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T15:21:42.897+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T15:21:42.902+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T152141, end_date=20250718T152142
[2025-07-18T15:21:42.913+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 252)
[2025-07-18T15:21:42.940+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T15:21:42.958+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T15:24:55.255+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:24:55.263+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:24:55.264+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:24:55.264+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T15:24:55.264+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:24:55.273+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T15:24:55.276+0000] {standard_task_runner.py:55} INFO - Started process 250 to run task
[2025-07-18T15:24:55.278+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpvpqmm2pd']
[2025-07-18T15:24:55.284+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T15:24:55.350+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host 25988e3bb701
[2025-07-18T15:24:55.407+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T15:24:55.408+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T15:24:55.408+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T15:24:55.416+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T15:24:56.513+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T15:24:56.513+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T15:24:56.514+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T15:24:56.520+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpy3xravc8/data/raw/adult.csv â€¦
[2025-07-18T15:24:56.520+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T15:24:56.578+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T15:24:56.579+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-18T15:24:56.579+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T15:24:56.579+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T15:24:56.579+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T15:24:56.579+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T15:24:56.579+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T15:24:56.579+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T15:24:56.579+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T15:24:56.580+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T15:24:56.580+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T15:24:56.580+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T15:24:56.580+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T15:24:56.580+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T15:24:56.580+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T15:24:56.580+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T15:24:56.580+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T15:24:56.580+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpy3xravc8/data/raw/adult.csv'
[2025-07-18T15:24:56.580+0000] {subprocess.py:93} INFO - 
[2025-07-18T15:24:56.581+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T15:24:56.696+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T15:24:56.704+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T15:24:56.707+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T152455, end_date=20250718T152456
[2025-07-18T15:24:56.715+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 250)
[2025-07-18T15:24:56.760+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T15:24:56.781+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T15:32:22.094+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:32:22.099+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:32:22.099+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:32:22.099+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T15:32:22.099+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:32:22.105+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T15:32:22.107+0000] {standard_task_runner.py:55} INFO - Started process 256 to run task
[2025-07-18T15:32:22.109+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpq0xam_oy']
[2025-07-18T15:32:22.112+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T15:32:22.142+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host 95d08d32c22b
[2025-07-18T15:32:22.172+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T15:32:22.172+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T15:32:22.173+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T15:32:22.178+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T15:32:23.044+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T15:32:23.045+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T15:32:23.045+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T15:32:23.051+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmp1vn5c27h/data/raw/adult.csv â€¦
[2025-07-18T15:32:23.051+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T15:32:23.085+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T15:32:23.085+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-18T15:32:23.085+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T15:32:23.085+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T15:32:23.085+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T15:32:23.086+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T15:32:23.086+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T15:32:23.086+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T15:32:23.086+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T15:32:23.086+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T15:32:23.086+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T15:32:23.086+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T15:32:23.086+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T15:32:23.086+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T15:32:23.086+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T15:32:23.086+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T15:32:23.087+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T15:32:23.087+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmp1vn5c27h/data/raw/adult.csv'
[2025-07-18T15:32:23.087+0000] {subprocess.py:93} INFO - 
[2025-07-18T15:32:23.087+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T15:32:23.192+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T15:32:23.199+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T15:32:23.202+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T153222, end_date=20250718T153223
[2025-07-18T15:32:23.208+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 256)
[2025-07-18T15:32:23.248+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T15:32:23.273+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T15:44:33.141+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:44:33.146+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:44:33.146+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:44:33.146+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T15:44:33.147+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:44:33.153+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T15:44:33.156+0000] {standard_task_runner.py:55} INFO - Started process 251 to run task
[2025-07-18T15:44:33.159+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmp53iw_lq0']
[2025-07-18T15:44:33.160+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T15:44:33.192+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host d7e53b8a5638
[2025-07-18T15:44:33.222+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T15:44:33.223+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T15:44:33.224+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T15:44:33.228+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T15:44:34.580+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T15:44:34.582+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T15:44:34.584+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T15:44:34.587+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpc1v6i0wa/data/raw/adult.csv â€¦
[2025-07-18T15:44:34.587+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T15:44:34.630+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T15:44:34.630+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-18T15:44:34.630+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T15:44:34.630+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T15:44:34.631+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T15:44:34.631+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T15:44:34.631+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T15:44:34.631+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T15:44:34.631+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T15:44:34.631+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T15:44:34.631+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T15:44:34.631+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T15:44:34.631+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T15:44:34.631+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T15:44:34.632+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T15:44:34.632+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T15:44:34.632+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T15:44:34.632+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpc1v6i0wa/data/raw/adult.csv'
[2025-07-18T15:44:34.632+0000] {subprocess.py:93} INFO - 
[2025-07-18T15:44:34.632+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T15:44:34.733+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T15:44:34.747+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T15:44:34.753+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T154433, end_date=20250718T154434
[2025-07-18T15:44:34.764+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 251)
[2025-07-18T15:44:34.804+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T15:44:34.820+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T15:46:15.057+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:46:15.065+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:46:15.066+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:46:15.066+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T15:46:15.067+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:46:15.081+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T15:46:15.085+0000] {standard_task_runner.py:55} INFO - Started process 256 to run task
[2025-07-18T15:46:15.089+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmp2vlq7dxx']
[2025-07-18T15:46:15.091+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T15:46:15.136+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host 1fae15ff5f05
[2025-07-18T15:46:15.175+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T15:46:15.176+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T15:46:15.176+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T15:46:15.182+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T15:46:16.468+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T15:46:16.468+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T15:46:16.469+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T15:46:16.481+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmpwhd27xeq/data/raw/adult.csv â€¦
[2025-07-18T15:46:16.481+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T15:46:16.517+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T15:46:16.517+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-18T15:46:16.517+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T15:46:16.518+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T15:46:16.518+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T15:46:16.518+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T15:46:16.518+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T15:46:16.518+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T15:46:16.518+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T15:46:16.518+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T15:46:16.518+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T15:46:16.518+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T15:46:16.519+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T15:46:16.519+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T15:46:16.519+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T15:46:16.519+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T15:46:16.519+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T15:46:16.519+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmpwhd27xeq/data/raw/adult.csv'
[2025-07-18T15:46:16.519+0000] {subprocess.py:93} INFO - 
[2025-07-18T15:46:16.519+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T15:46:16.638+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T15:46:16.653+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T15:46:16.656+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T154615, end_date=20250718T154616
[2025-07-18T15:46:16.665+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 256)
[2025-07-18T15:46:16.698+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T15:46:16.721+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T15:54:58.563+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:54:58.570+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [queued]>
[2025-07-18T15:54:58.573+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:54:58.574+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T15:54:58.574+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T15:54:58.584+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): feature_engineering> on 2025-07-17 00:00:00+00:00
[2025-07-18T15:54:58.587+0000] {standard_task_runner.py:55} INFO - Started process 251 to run task
[2025-07-18T15:54:58.590+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'feature_engineering', 'scheduled__2025-07-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpvuzm1zq0']
[2025-07-18T15:54:58.591+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask feature_engineering
[2025-07-18T15:54:58.621+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.feature_engineering scheduled__2025-07-17T00:00:00+00:00 [running]> on host e1a2c151e318
[2025-07-18T15:54:58.649+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=feature_engineering
AIRFLOW_CTX_EXECUTION_DATE=2025-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-17T00:00:00+00:00
[2025-07-18T15:54:58.651+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T15:54:58.651+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/engineer.py mode=feature']
[2025-07-18T15:54:58.656+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T15:54:59.689+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
[2025-07-18T15:54:59.689+0000] {subprocess.py:93} INFO - See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
[2025-07-18T15:54:59.689+0000] {subprocess.py:93} INFO -   ret = run_job(
[2025-07-18T15:54:59.695+0000] {subprocess.py:93} INFO - Loading raw data from /tmp/***tmp9aqq2i10/data/raw/adult.csv â€¦
[2025-07-18T15:54:59.696+0000] {subprocess.py:93} INFO - Error executing job with overrides: ['mode=feature']
[2025-07-18T15:54:59.730+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T15:54:59.730+0000] {subprocess.py:93} INFO -   File "/app/scripts/engineer.py", line 31, in main
[2025-07-18T15:54:59.730+0000] {subprocess.py:93} INFO -     FeatureEngineer(cfg).run()
[2025-07-18T15:54:59.730+0000] {subprocess.py:93} INFO -   File "/app/src/features/engineering.py", line 15, in run
[2025-07-18T15:54:59.731+0000] {subprocess.py:93} INFO -     df = pd.read_csv(self.raw_path)
[2025-07-18T15:54:59.731+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2025-07-18T15:54:59.731+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-07-18T15:54:59.731+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
[2025-07-18T15:54:59.731+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-07-18T15:54:59.731+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
[2025-07-18T15:54:59.731+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-07-18T15:54:59.731+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
[2025-07-18T15:54:59.732+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-07-18T15:54:59.732+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
[2025-07-18T15:54:59.732+0000] {subprocess.py:93} INFO -     self.handles = get_handle(  # type: ignore[call-overload]
[2025-07-18T15:54:59.732+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
[2025-07-18T15:54:59.732+0000] {subprocess.py:93} INFO -     handle = open(
[2025-07-18T15:54:59.732+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/***tmp9aqq2i10/data/raw/adult.csv'
[2025-07-18T15:54:59.732+0000] {subprocess.py:93} INFO - 
[2025-07-18T15:54:59.733+0000] {subprocess.py:93} INFO - Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-07-18T15:54:59.849+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T15:54:59.858+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T15:54:59.861+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=feature_engineering, execution_date=20250717T000000, start_date=20250718T155458, end_date=20250718T155459
[2025-07-18T15:54:59.868+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 251)
[2025-07-18T15:54:59.890+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T15:54:59.908+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
